### PR TITLE
[GH-#299] Fixes a bug where an invalid transaction would be mined

### LINKED ISSUE #299: transactions resulting in invalid chainstate get mined
will provide a test case in code

### PR DESCRIPTION
**Pull request by gspasov**
resolves #299

### CODE REVIEW

File: apps/aecore/test/aecore_tx_test.exs [hunk 1]
```diff
@@ -73,4 +79,29 @@ defmodule AecoreTxTest do
...
+    priv_key = Wallet.get_private_key()
+    {:ok, signed_tx} = SignedTx.sign_tx(tx_data, priv_key)
+
+    :ok = Pool.add_transaction(signed_tx)
+
+    :ok = Miner.mine_sync_block_to_chain()
+
+    # We should have only made two coinbase transactions
+    assert Enum.count(Chain.chain_state().accounts) == 1
+    assert Chain.chain_state().accounts[Wallet.get_public_key()].balance == 200
```
Comment (thepiwo) [inline apps/aecore/test/aecore_tx_test.exs]: can you reduce value to 200 and fee to 50, mine one more block, it should be included by then

Comment (gspasov) [reply apps/aecore/test/aecore_tx_test.exs]: @thepiwo I should mine 2 more blocks, because the miner will need 300 tokens so that the transaction is valid, so the transaction will be mined on the 4th mined block

Comment (thepiwo) [reply apps/aecore/test/aecore_tx_test.exs]: yes realized that, good!
