### PR TITLE
[GH-#393] fixed nil.refs error

### LINKED ISSUE #393: nil.refs error in add_validated_block function
There is an error that appear when running two separate nodes. When you run two synchronized nodes (one is mining) for the first time, everything is ok. But when you try to restart them there is an error:

[error] GenServer Aecore.Chain.Worker terminating
** (UndefinedFunctionError) function nil.refs/0 is undefined (module nil is not available)
    nil.refs()
    (aecore) lib/aecore/chain/worker.ex:353: anonymous fn/3 in Aecore.Chain.Worker.handle_call/3

https://github.com/aeternity/elixir-node/blob/b8c5a1e2c9db022731edae0a0aaf506c1b4a4fe4/apps/aecore/lib/aecore/chain/worker.ex#L353   -   the line where error appears

### PR DESCRIPTION
**Pull request by 0legIv**
resolves #393

### CODE REVIEW

**Comment by thepiwo** [comment]
Please adjust to @cytadela8 comments and propose a follow-up task, to investigate the underlaying issue.

**Comment by thepiwo** [comment]
@gspasov @cytadela8 can you review?

File: apps/aecore/lib/aecore/chain/worker.ex [hunk 1]
```diff
@@ -350,12 +350,16 @@ defmodule Aecore.Chain.Worker do
...
+        with true <- Map.has_key?(blocks_data_map, prev),
+             {:ok, hash} <- Enum.fetch(blocks_data_map[prev].refs, i) do
+          [hash | acc]
+        else
+          :error ->
             acc
 
-          hash ->
-            [hash | acc]
+          _ ->
```
Comment (cytadela8) [inline apps/aecore/lib/aecore/chain/worker.ex]: this can proably be: `false ->`
