### PR TITLE
[GH-#466] Fixed bug where we can't get blocks out of memory

### LINKED ISSUE #466: Fail to get block by height while syncing
Raised error is `key :block not found`. [Link](https://github.com/aeternity/elixir-node/blob/master/apps/aecore/lib/aecore/chain/worker.ex#L157) to the case.

How to reproduce it:

First node A mines few blocks then node B is synced with node A. Then node B is restarted and is synced with node A (still mining) again.

### PR DESCRIPTION
**Pull request by gspasov**
resolves #466 and #465

### CODE REVIEW

File: apps/aecore/lib/aecore/chain/worker.ex [hunk 1]
```diff
@@ -411,7 +397,7 @@ defmodule Aecore.Chain.Worker do
         ## Transfrom from chain state
         :chain_state => %{
           new_block_hash =>
-            transfrom_chainstate(:from_chainstate, Map.from_struct(new_chain_state))
+            transfrom_chainstate(:from_chainstate, {:ok, Map.from_struct(new_chain_state)})
```
Comment (rdimitrovbg) [inline apps/aecore/lib/aecore/chain/worker.ex]: Would you give the correct function name?

File: apps/aecore/lib/aecore/chain/worker.ex [hunk 2]
```diff
@@ -443,7 +429,7 @@ defmodule Aecore.Chain.Worker do
       Persistence.batch_write(%{
         :chain_state => %{
           new_block_hash =>
-            transfrom_chainstate(:from_chainstate, Map.from_struct(new_chain_state))
+            transfrom_chainstate(:from_chainstate, {:ok, Map.from_struct(new_chain_state)})
```
Comment (rdimitrovbg) [inline apps/aecore/lib/aecore/chain/worker.ex]: Would you give the correct function name?
