### PR TITLE
[GH-721] Miner crash workaround

### LINKED ISSUE #721: Miner crashes sometimes
When using the lean16 miner our miner process sometimes crashes.
On a clean chain the miner crashes after mining 10-20 blocks.
When I tried using the mean28-avx2 miner the same problem occurs.

### PR DESCRIPTION
**Pull request by grzegorz225**
This PR will prevent the miner from crashing on long runs.
I've tried to find the underlying reason for the crashes but I couldn't find it. It seems that very rarely in the multi threaded native miner a race condition occurs which crashes the miner. I've added the functionality of ignoring these crashes.

resolves #721

### CODE REVIEW

File: apps/aecore/lib/aecore/miner/worker.ex [hunk 1]
```diff
@@ -96,6 +102,19 @@ defmodule Aecore.Miner.Worker do
     mine_sync_block(Pow.generate(cheader), cblock)
   end
 
+  defp mine_sync_block(
```
Comment (d-velev) [inline apps/aecore/lib/aecore/miner/worker.ex]: Is this case needed when we have the check for != {:error, :miner_was_stopped} above?
