### PR TITLE
[GH-660] fix credo and test issues

### LINKED ISSUE #660: fix credo and test issues

### PR DESCRIPTION
**Pull request by thepiwo**
resolves #660

### CODE REVIEW

File: apps/aecore/test/aecore_chain_test.exs [hunk 1]
```diff
@@ -19,7 +19,7 @@ defmodule AecoreChainTest do
     TestUtils.clean_blockchain()
 
     tests_pow = Application.get_env(:aecore, :pow_module)
-    Application.put_env(:aecore, :pow_module, Aecore.Pow.Cuckoo)
+    Application.put_env(:aecore, :pow_module, Aecore.Pow.Mock)
```
Comment (cytadela8) [inline apps/aecore/test/aecore_chain_test.exs]: If you want to disable Cuckoo and use Mock on those tests remove this line, line 21 and 26.

Comment (thepiwo) [reply apps/aecore/test/aecore_chain_test.exs]: I will, thanks

**Comment by thepiwo** [comment]
@DanielaIvanova @cytadela8 can you re-review?
