### PR TITLE
[GH-#266] fixed compiler warnings

### LINKED ISSUE #266: fix elixir compiler warnings

### PR DESCRIPTION
**Pull request by thepiwo**
excluding tests

closes #266

### CODE REVIEW

File: apps/aecore/lib/aecore/persistence/worker.ex [hunk 1]
```diff
@@ -166,7 +165,7 @@ defmodule Aecore.Persistence.Worker do
       |> Enum.into([])
     else
         Enum.reduce(Rox.stream(blocks_family), [],
-          fn({hash, %{header: %{height: height}} = block} = record, acc) ->
+          fn({_hash, %{header: %{height: height}} = _block} = record, acc) ->
```
Comment (d-velev) [inline apps/aecore/lib/aecore/persistence/worker.ex]: I think "= _block" can be removed

Comment (thepiwo) [reply apps/aecore/lib/aecore/persistence/worker.ex]: yes, right
